config/routes.rb
Trendhop::Application.routes.draw do

  resources :feeds do
    collection do
      get 'subscribe'
      post :subscribe
      get 'unsubscribe'
      post :unsubscribe

      get 'create_feed'
      post :create_feed
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :friends do
    collection do
      get :create, :as => :create
      delete :destroy, :as => :destroy
    end
  end

  resources :groups

  resources :friends

  resources :search

  resources :posts do
    collection do
      get 'like'
      post :like
      get 'unlike'
      post :unlike
      get 'retrend'
      post :retrend
      get 'untrend'
      post :untrend
      get 'hide'
      post :hide
    end
    resources :comment_posts
  end

  resources :trends do
    collection do
      get 'follow'
      post :follow
      get 'unfollow'
      post :unfollow
    end
  end

  match 'blogs/refresh' => 'blogs#refresh'
  resources :blogs do
    collection do
      get 'filter'
      post :filter
    end
    resources :trends
  end

  resources :users do
    resources :blogs
  end

  root :to => 'home#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base

  has_many :entry_feeds, :dependent => :destroy
  has_many :user_feeds

  belongs_to :feed_category

  def self.update_all
    feeds = Feed.all
    feeds.each do |f|
      EntryFeed.create_from_feed(f)
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate_user!
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

      # fetching a single feed
  #@feed = Feedzirra::Feed.fetch_and_parse("http://feeds.feedburner.com/PaulDixExplainsNothing")

 # @entries = @feed.entries

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])
    @entries = EntryFeed.where(:feed_id => @feed.id)

    if @entries.blank?
      EntryFeed.create_from_feed(@feed)
      @entries = EntryFeed.where(:feed_id => @feed.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @feed }
    end
  end

  def create
    @feed = Feed.new(params[:feed])

    @e_feed = Feedzirra::Feed.fetch_and_parse(@feed.url)

    respond_to do |format|
      format.html #test.html.erb
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create_feed
    @feed = Feed.new(params[:feed])

    respond_to do |format|
      if @feed.save
        EntryFeed.create_from_feed(@feed)
        format.html { redirect_to @feed, :notice => 'Feed was successfully created.' }
        format.json { render :json => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, :notice => 'Feed was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :ok }
    end
  end

  def subscribe
    @feed = Feed.where(:id => params[:feed_id]).first
    subscribe = UserFeed.new(:user_id => current_user.id, :feed_id => @feed.id, :feed_group_id => @feed.feed_category_id)
    if subscribe.save
      flash[:notice] = "You have Subscribed to this Blog!"
      redirect_to feeds_path
    else
      flash[:notice] = "There was an error!!!!"
      redirect_to feeds_path
    end
  end

  def unsubscribe
    @feed = Feed.where(:id => params[:feed_id]).first
    subscribe = UserFeed.where(:user_id => current_user.id, :feed_id => @feed.id).first
    subscribe.destroy

    respond_to do |format|
      format.html { redirect_to feeds_path, :notice => "You have Unsubscribed to this post!" }
      format.json { head :ok }
    end
  end


end

app/helpers/feeds_helper.rb
module FeedsHelper

  def is_subscribed?(feed)
    feed = UserFeed.where(:user_id => @current_user.id, :feed_id => feed.id).first
    feed
  end

end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :feed_category_id %><br />
    <%= f.collection_select(:feed_category_id, FeedCategory.all, :id, :name, :prompt => true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/create.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @e_feed.title %>
</p>

<p>
  <b>Url:</b>
  <%= @e_feed.url %>
</p>



<p>
  <b>Sample entries:</b>
</p>
<hr/>

<% test_title = 0%>
<% test_author = 0%>
<% test_summary = 0%>
<% test_content = 0%>
<% test_trends = 0%>
<% test_date =  0%>

<% @e_feed.entries.each do |entry| %>
  <h2><%= entry.title %></h2>
  <% test_title = test_title + (entry.title.blank? ? 0 : 1) %>
  <h5><b>By: <%= entry.author%>, posted on <%= entry.published %></b></h5>
  <% test_date = test_date + (entry.published.blank? ? 0 : 1) %>
  <p><b>Summary:</b> <%= raw(entry.summary) %></p>
  <% test_summary = test_summary + (entry.summary.blank? ? 0 : 1) %>
  <p><b>Content:</b> <%= raw(entry.content)%>
    <% test_content = test_content + (entry.content.blank? ? 0 : 1) %>
  <p><b>Trends:></b> <% entry.categories.each do |trend| %> <%= trend%>, <%end%></p>
  <% test_trends = test_trends + (entry.categories.blank? ? 0 : 1) %>
  <hr/><br/><hr></br>
<%end%>

<% content_for :left_menu do %>
<p><b>Test Results:</b>
  <ul style="padding: 0; margin: 0;">
    <li>Title parse:  <b class=<%= test_title > 2 ? "green" : "red"%> >  <%= test_title > 2 ? "Passed" : "Failed" %></b></li>
    <li>Author parse: <b class=<%= test_author > 2 ? "green" : "red"%> > <%= test_author > 2 ? "Passed" : "Failed"%></b></li>
    <li>Date parse: <b class=<%= test_date > 2 ? "green" : "red"%> > <%= test_date > 2 ? "Passed" : "Failed"%></b></li>
    <li>Summary parse: <b class=<%= test_summary > 2 ? "green" : "red"%> > <%= test_summary > 2 ? "Passed" : "Failed"%></b></li>
    <li>Content parse: <b class=<%= test_content > 2 ? "green" : "red"%> > <%= test_content > 2 ? "Passed" : "Failed"%></b></li>
    <li>Trends parse: <b class=<%= test_trends > 2 ? "green" : "red"%> > <%= test_trends > 2 ? "Passed" : "Failed"%></b></li>       
          
</p>
<hr/>
<%= form_for @feed, :url => {:action => "create_feed"} do |f| %>
  <%= f.hidden_field :name, :value => @feed.name %>
  <%= f.hidden_field :url, :value => @feed.url%>
  <%= f.hidden_field :feed_category_id, :value => @feed.feed_category_id %>
  <%= f.submit %>
<%end%>
<%= link_to 'Go Back', feeds_path %>
<%end%>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<% content_for :left_menu do%>
  <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
  <h4 style="font-size: 16px; font-weight: bold;">Don't see a Feed you want?</h4>
  <p>Just recommend one! </p>
<%end%>

<h1>Browse Through Feeds</h1>
<% if can? :manage, Feed %>
  <%= link_to 'Test New Feed & add', new_feed_path %><br/>

<%end%>

<% FeedCategory.all.each do |cat|%>
  <div class="feed_table">
      <div class="feed_name"><%= cat.name%></div>

      <div class="table">
        <% cat.feeds.each do |feed| %>
          <div class="table-row">
            <div class="fl" id="name"><%= link_to feed.name, feed %></div>
            <% if is_subscribed?(feed).blank? %>
              <div class="fr option"><%= link_to "Subscribe", subscribe_feeds_path(:feed_id => feed.id), :id=>"subscribe"%></div>
            <% else %>
              <div class="fr option"><%= link_to "Unsubscribe", unsubscribe_feeds_path(:feed_id => feed.id), :id=>"unsubscribe" %></div>
            <%end%>
            <% if can? :manage, Feed %>
              <div class="clear"></div>
              <div><%= link_to 'Edit', edit_feed_path(feed) %> | | <%= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete %></div>
              <br/>
            <%end%>
            <div class="clear"></div>
          </div>

        <% end %>
      </div>
  </div>
<%end%>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>

<p>
</p>
<hr/>
<% @entries.each do |entry| %>
  <h2><%= entry.title %></h2>
  <h5>By <%#= entry.author%>, posted on <%= entry.published_at %></h5>
  <p><b>Quick Summary: </b> <%= strip_tags(raw(entry.summary)) %></p>
  <hr/>
  <p><b>Content: </b> <%= strip_tags(raw(entry.content)) %>
  <p><b>Trends: </b><% entry.trends.each do |trend| %><%= trend.name %><br/><%end%> </p>
  <hr/><br/>
<%end%>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>