config/routes.rb
Trendhop::Application.routes.draw do

  resources :feeds do
    collection do
      get 'subscribe'
      post :subscribe
      get 'unsubscribe'
      post :unsubscribe

      get 'create_feed'
      post :create_feed
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :friends do
    collection do
      get :create, :as => :create
      delete :destroy, :as => :destroy
    end
  end

  resources :groups

  resources :friends

  resources :search

  resources :posts do
    collection do
      get 'like'
      post :like
      get 'unlike'
      post :unlike
      get 'retrend'
      post :retrend
      get 'untrend'
      post :untrend
      get 'hide'
      post :hide
    end
    resources :comment_posts
  end

  resources :trends do
    collection do
      get 'follow'
      post :follow
      get 'unfollow'
      post :unfollow
    end
  end

  match 'blogs/refresh' => 'blogs#refresh'
  resources :blogs do
    collection do
      get 'filter'
      post :filter
    end
    resources :trends
  end

  resources :users do
    resources :blogs
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :birth_day, :birth_month, :birth_year, :city, :state, :sex, :email, :password, :password_confirmation, :remember_me, :role

  has_many :blogs, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :user_trends, :dependent => :destroy
  has_many :trends, :through => :user_trends

  has_many :user_friends, :dependent => :destroy
  has_many :friends, :through => :user_friends

  has_many :user_following_trends
  has_many :trends, :through => :user_following_trends

  has_many :groups, :dependent => :destroy

  has_many :user_likes
#  has_many :likes, :through => :user_likes

  has_many :comment_posts

  has_many :roles


  #scope :with_at_least, lambda {|number_of_bottles| where(:quantity_available.gte => number_of_bottles)}

  ROLES = %w[admin moderator standard]

  SEX = %w[male female]

  # def role_symbols
  #   [role.to_sym]
  # end
  def friend_group(user)
    friend = UserFriend.where(:user_id => user.id, :friend_id=> self.id).first
  end


  def full_name
    [first_name,last_name].join(" ")
  end


  def birth_date
    [birth_month, birth_day, birth_year].join("/")
  end

  def address
    [city, state_id].join(",")
  end

  def age
    now = Time.now
    birthday = Date.civil(self.birth_year, self.birth_month, self.birth_day)
    age = (now.year - birthday.year) - (now.yday < birthday.yday ? 1 : 0)
    age;
  end

  define_index do
    indexes first_name
    indexes last_name
    indexes [first_name, last_name], :as => :full_name
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_filter :authenticate_user!
    load_and_authorize_resource
    skip_load_resource :only => :edit
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @section = params[:section].blank? ? "about" : params[:section]
    @friend = is_friend?(@user)
    @blogs = @user.blogs
    @post = Post.new
    @posts = @user.posts
    @trends = @user.trends
    @friends = @user.friends


    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
 #   @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user = check_user(@user)
  end

  # POST /users
  # POST /users.json
#   def create
# #    @user = User.new(params[:user])
#
#
#     respond_to do |format|
#       if @user.save
#         create_groups(@user)
#         format.html { redirect_to @user, :notice => 'User was successfully created.' }
#         format.json { render :json => @user, :status => :created, :location => @user }
#       else
#         format.html { render :action => "new" }
#         format.json { render :json => @user.errors, :status => :unprocessable_entity }
#       end
#     end
#   end

  # PUT /users/1
  # PUT /users/1.json
  def update
 #   @user = User.find(params[:id])
    check_user(@user)

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
 #   @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  private

  def check_user(user)
    if user != current_user
      check = current_user.role == "admin" ? user : current_user
      return check
      # redirect_to root_url, :notice => "Incorrect credentials"
    else
      return current_user
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.number_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.collection_select(:sex, User::SEX, :to_s, :humanize, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :birth_day %><br />
    <%= f.number_field :birth_day %>
  </div>
  <div class="field">
    <%= f.label :birth_month %><br />
    <%= f.number_field :birth_month %>
  </div>
  <% if current_user.role == 'admin'%>
    <div class="field">
      <%= f.label :role %><br />
      <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
    </div>
  <%end%>
  <div class="field">
    <%= f.label :birth_year %><br />
    <%= f.number_field :birth_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_friends.html.erb
<ul class="friends_show">
<% @friends.each do |friend|%>
  <% @user_friend = friend.friend_group(current_user)%>
  <%# raise @user_friend.inspect%>
  <%# raise current_user.groups.inspect%>
  <li>
    <div>
      <div class="name fl"><%= friend.full_name %></div>
      <div class='group fl'>
      <%if @user != current_user%>
        <%= @user_friend.name %>
      <% else%>
        <%= form_for @user_friend, :url => {:controller => :friends, :action => :update, :real_id => @user_friend.id}, :remote => true do |f|%>
            <%= f.collection_select(:group_id, current_user.groups, :id, :name, :prompt => true ) %>
        <%end%>
      <%end%>
      </div>
      <div class="clear"></div>
    </div>
  </li>
<% end%>
</ul>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div id="user_search">
<% if @users.blank?%>
  <h3>There are no users!</h3>
<%else%>
  <% @users.each do |user| %>
    <div class="table_row">
      <div class="fl name"><%= link_to user.full_name, user %></div>
      <div class="clear"></div>
      <div class="fl sex"><%= user.sex %></div>
      <div class="fl birth"><%= user.birth_date%></div>
      <div class="clear"></div>
      <div class="fl location"><%= user.city %>, <%= user.state_id %></div>
      <div class="clear"></div>
      <div class="fl count">Posts: <%= user.posts.count %></div>
      <div class="fl count">Trends: <%= user.trends.count %></div>
      <% if can? :manage, user%>
        <div class="fl"><%= link_to 'Edit', edit_user_path(user) %></div>
        <div><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></div>
      <%end%>
    </div>
    <div class="clear"></div>
  <% end %>
    <div class="clear"></div>
<%end%>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for :left_menu do%>
 <br/><br/>
   <ul class="trend_filters">
     <% sections = ["about","posts", "trends", "likes", "friends"]%>
     <% sections.each do |section| %>
       <% if @section== section%>
         <%= link_to user_path(@user, :section => section), :class=>"filter-link", :id=>"active-filter" do%>
           <li class="filter">
                <span><%= section.humanize %> </span>
           </li>
         <%end%>
       <%else%>
         <%= link_to user_path(@user, :section => section), :class=>"filter-link" do%>
           <li class="filter">
                <span><%= section.humanize %> </span>
           </li>
         <%end%>
       <%end%>
     <%end%>
   </ul>
 <%end%>

<% content_for :page_title do%>
<div class="user-top">
  <div class="fr">
    <%if @user != current_user%>
    <%# raise @friend.inspect%>
      <% if @friend.blank?%>
        <div class="fr">
          <%= link_to create_friends_path(:id => @user.id) do%>
            <div role="button" class="button add_friend">Follow <%=@user.first_name %> </div>
          <%end%>
        </div>
      <% else%>
        <div class="fr">
          <%= link_to destroy_friends_path(:id => @user.id), :confirm => "Stop following?", :method => :delete do%>
            <div role="button" class="button remove_friend">Stop Following </div>
          <%end%>
        </div>
      <%end%>
    <%end%>
    <% if can? :update, @user %>
      <div class='clear'></div>
      <div class="fr">
        <%= link_to edit_user_path(@current_user) do%>
          <div role="button" class="button edit">Edit </div>
        <% end%>
      </div>
    <%end%>
  </div>
  <div>
    <div class="fl">
      <%= image_tag ("/assets/Profile.png"), :style =>"height:100px; width:80px;" %>
    </div>
    <div class="fl">
      <div class="first-name"><%= @user.first_name %></div>
      <div class="last-name"><%= @user.last_name %> </div>
    </div>
    <div class="clear"></div>
  </div>
</div>
<% end%>

<div class="content" id="user_show">

<% case @section %>
  <% when "about"%>

  <div class="user-about">
    <div class="about-section">
      <div class="about-subsection">
        <span>Birthday</span>
      </div>
      <div class="info-subsection">
        <span><%= @user.birth_date %></span>
      </div>
      <div class="clear"></div>
    </div>

    <div class="about-section">
      <div class="about-subsection">
        <span>Gender</span>
      </div>
      <div class="info-subsection">
        <span><%= @user.sex.humanize %></span>
      </div>
      <div class="clear"></div>
    </div>

    <div class="about-section">
      <div class="about-subsection">
        <span>Occupation</span>
      </div>
      <div class="info-subsection">
        <span>Student </span>
      </div>
      <div class="clear"></div>
    </div>

    <div class="about-section">
      <div class="about-subsection">
        <span>Location</span>
      </div>
      <div class="info-subsection">
        <span> <%= @user.city%>, <%= @user.state_id %>
      </div>
      <div class="clear"></div>
    </div>

    <div class="about-section">
      <div class="about-subsection">
        <span>Education</span>
      </div>
      <div class="info-subsection">
        <span>College: </span>
        <div class="fr">Montclair State University </div>
      </div>
      <div class="clear"></div>
    </div>

  </div>

  <% when "posts"%>

    <p>
      <b>Posts by You: </b>
      <%= render :partial => "posts/index"%>
    </p>

  <% when "trends"%>
    <p>
      <b>Trends: </b>
      <%= render :partial => "trends/index" %>
    </p>
  <% when "likes" %>
    <div id="like_index">
    <% @user.user_likes.each do |like|%>
      <% case like.source_type%>
        <% when "Post"%>
          <div class="post">
          <% @post1 = Post.where(:id => like.source_id).first %>
          <%= render :partial => "posts/post"%>
          </div>
        <%when "Trend"%>

      <%end%>
    <%end%>
    </div>
  <% when "friends"%>
  <% if !@friends.blank? %>
    <%= render :partial => "users/friends"%>
  <% else%>
    <p>You have no friends?!?! </p>
  <%end%>
<% end%>

</div>