config/routes.rb
Trendhop::Application.routes.draw do

  resources :feeds do
    collection do
      get 'subscribe'
      post :subscribe
      get 'unsubscribe'
      post :unsubscribe

      get 'create_feed'
      post :create_feed
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :friends do
    collection do
      get :create, :as => :create
      delete :destroy, :as => :destroy
    end
  end

  resources :groups

  resources :friends

  resources :search

  resources :posts do
    collection do
      get 'like'
      post :like
      get 'unlike'
      post :unlike
      get 'retrend'
      post :retrend
      get 'untrend'
      post :untrend
      get 'hide'
      post :hide
    end
    resources :comment_posts
  end

  resources :trends do
    collection do
      get 'follow'
      post :follow
      get 'unfollow'
      post :unfollow
    end
  end

  match 'blogs/refresh' => 'blogs#refresh'
  resources :blogs do
    collection do
      get 'filter'
      post :filter
    end
    resources :trends
  end

  resources :users do
    resources :blogs
  end

  root :to => 'home#index'

end

app/models/trend.rb
class Trend < ActiveRecord::Base

  has_many :post_trends
  has_many :post_contents, :through => :post_trends

  belongs_to :user_following_trends

  has_many :entry_feed_trends

  has_many :posts, :through => :post_contents

  has_many :entry_feed_trends
  has_many :entry_feeds, :through => :entry_feed_trends

  has_many :user_trends
  has_many :users, :through => :user_trends

  has_many :trend_hops
  has_many :trends, :through => :trend_hops

  scope :set_range, lambda {|field| where (["trends.updated_at >= ?", eval("Time.now-1.#{field}") ])}  #field = [day, week, month, year]
  scope :set_men, joins(:users).where(["users.sex = 0"])
  scope :set_women, joins(:users).where(["users.sex = 1"])

  # scope :user_follow, lambda {|user| {:joins => :user_following_trends, :conditions => ["user_following_trends.user_id == #{user}"] }}

# Trend filtering #
  #Ages: 13 & younger, 13-15, 16-18, 19-21, 21-24, 25-29, 30-35, 36-40,
  def age_set(age)
    age = self.where(:user)
  end

  def list
    self.trends.map(&:name)
  end

  define_index do
    indexes :name
  end


  private

  def self.entry_feed_trend(trend)
    trend_get = trend.delete("!").delete("@").delete("#").delete("*").delete("(").delete(")").delete("?").delete(".").delete(",").delete("<").delete(">").delete("/").delete('\\').delete("-")
    trend_find = Trend.where(:name => trend_get).first
    if trend_find.blank?
      create!(
        :name         => trend_get,
        :trend_count  => 0,
        :like_count   => 0
        )
      trend_find = Trend.where(:name => trend_get).first
    end
    return trend_find
  end

end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
#  layout "trends", :except => [:index]
# layout 'application', :only => [:index]

  before_filter :authenticate_user!

 #   load_and_authorize_resource, :only => [:index, :new, :edit, :create, :update, :destroy ]

  # GET /trends
  # GET /trends.json
  def index
    @trend_filter = params[:filter]

    @trends = case params[:filter]
      when "recent" then Trend.order("created_at DESC")
      when "popular" then Trend.order("trend_count DESC")
      when "today" then Trend.set_range("day")
      when "past_week" then Trend.set_range("week")
      when "past_month" then Trend.set_range("month")
      when "men" then Trend.set_men
      when "women" then Trend.set_women
      else Trend.order("created_at DESC")
    end
  #  raise @trends.inspect

    @posts = Post.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trends }
    end
  end

  # GET /trends/1
  # GET /trends/1.json
  def show
    @trend_search = params[:id].to_s
    @trends = Trend.search :conditions => {:name => params[:id] }
    if @trends.blank?
      @trends = Trend.where(:name => params[:id])
    end

    @trend_hops = trend_hops(@trends)
    @posts = get_trend_posts(@trends)
    @blogs = get_trend_blogs(@trend_search)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @trend }
    end
  end

  # GET /trends/new
  # GET /trends/new.json
  def new
    @trend = Trend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @trend }
    end
  end

  # GET /trends/1/edit
  def edit
    @trend = Trend.find(params[:id])
  end

  # POST /trends
  # POST /trends.json
  def create
    @trend = Trend.new(params[:trend])

    respond_to do |format|
      if @trend.save
        format.html { redirect_to @trend, :notice => 'Trend was successfully created.' }
        format.json { render :json => @trend, :status => :created, :location => @trend }
      else
        format.html { render :action => "new" }
        format.json { render :json => @trend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trends/1
  # PUT /trends/1.json
  def update
    @trend = Trend.find(params[:id])

    respond_to do |format|
      if @trend.update_attributes(params[:trend])
        format.html { redirect_to @trend, :notice => 'Trend was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @trend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trends/1
  # DELETE /trends/1.json
  def destroy
    @trend = Trend.find(params[:id])
    @trend.destroy

    respond_to do |format|
      format.html { redirect_to trends_url }
      format.json { head :ok }
    end
  end

  def follow
    session[:return_to] ||= request.referer
    @trend = Trend.find(params[:id])
    @user_follow = UserFollowingTrend.new(:user_id => current_user.id, :trend_id => @trend.id)

    if @user_follow.save
      flash[:notice] = "Oh are not following #{@trend.name}"
      redirect_to session[:return_to]
    else
      flash[:notice] = "There was an error!!!!"
    end

  end

  def unfollow
    session[:return_to] ||= request.referer
    @trend = Trend.find(params[:id])
    @user_follow = UserFollowingTrend.where(:user_id => current_user.id, :trend_id => @trend.id).first

    @user_follow.destroy

    respond_to do |format|
      format.html {redirect_to session[:return_to]}
      format.json {head :ok}
    end
  end






  private

  def trend_hops(trends)
    hops = []
    trends.each do |trend|
      trend.trends.order("trend_count DESC").limit(15).each do |hop|
        hops << hop
      end
    end
    hops
  end

  def get_trend_posts(trends)
    posts = []
    trends.each do |trend|
      trend.posts.no_retrends.each do |post|
        posts << post
      end
    end
    posts
  end

  def get_trend_blogs(trend)
    blogs =[]
    EntryFeed.search(trend, :order => :published_at, :sort_mode => :asc).each do |blog|
        blogs << blog
    end
    if blogs.blank?
      tr = Trend.where(:name => trend).first
      EntryFeedTrend.where(:trend_id => tr.id).each do |blog|
        blogs << blog.entry_feed
      end
    end
    blogs
  end

end

app/helpers/trends_helper.rb
module TrendsHelper

  def list_trend_categories(trends)
    categories = []
    trends.each do |trend|
      categories <<" " + trend.trend_category_id unless trend.trend_category_id.blank?
    end
    categories
  end

  def like_counts(trends)
    count = 0
    trends.each do |trend|
      count = count + trend.like_count unless trend.like_count.blank?
    end
    count
  end

  def trend_counts(trends)
    count = 0
    trends.each do |trend|
      count = count + trend.trend_count unless trend.trend_count.blank?
    end
    count
  end

  def blog_counts(trends)
    count = 0
    trends.each do |trend|
      count = count + trend.entry_feeds.count unless trend.entry_feeds.blank?
    end
    count
  end

end

app/views/trends/_form.html.erb
<%= form_for(@trend) do |f| %>
  <% if @trend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trend.errors.count, "error") %> prohibited this trend from being saved:</h2>

      <ul>
      <% @trend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>Title </p>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :trend_category_id %><br />
    <%= f.number_field :trend_category_id %>
  </div>
  <div class="field">
    <p>What's Trending? </p>
    <%= f.text_area  :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trends/_index.html.erb
<div class="content" id="trends">
  <% if @trends.blank? %>
    <h3>There are no Trends!</h3>
  <%else%>
  <ul class="trends_list">
    <% @trends.each do |trend| %>
       <% if !trend.post_contents.blank? %>
       <li class="trend">
       <div class="trend_title"># <%= link_to trend.name, trend_path(trend.name), :id=> "trend"%></div>
       <div class="clear"></div>
         <div class="trend_info fl">
           <span style="font-size: 25px; font-weight:bold;"><%= trend.trend_count %></span> People trending<br/>
           <span style="font-size: 25px; font-weight:bold;"><%= trend.entry_feeds.count%></span> Blogs trending<br/>
           <span style="font-size: 25px; font-weight:bold;"><%= trend.like_count%></span> Likes
         </div>
         <div class="trend_contents fl">
           <div class="trend_list fl">
             <div class="subsection_title">Recent Posts: </div>
             <ul class="list_items">
               <% trend.post_contents.each do |post| %>
               <% post.posts.each do |p|%>
                 <% if !p.blank? || p != ""%>
                   <% @link_post = p%>
                 <%end%>
               <%end%>
               <li>  <%= link_to post.content, post_path(@link_post), :id=> "post" %><br/></li>
               <% end%>
             </ul>
           </div>
           <div class="trend_list fl">
             <div class="subsection_title">Recent Blogs: </div>
             <ul class="list_items">
               <% trend.entry_feeds.each do |entry| %>
               <li>  <%= link_to entry.title, blog_path(entry), :id=> "entry" %><br/></li>
               <% end%>
             </ul>
           </div>
         </div>


         <div class="clear"></div>
         <div class="trend_hops" class="fl">
           <span class="trend_section_info fl">Hop to a related trend: </span>
           <ul class="trend_hop fl">
             <% trend.trends.order("trend_count DESC").limit(6).each do |hop| %>
             <li>  <%= link_to hop.name, trend_path(hop.name), :id => "trend" %><br/></li>
             <% end%>
           </ul>
         </div>
         <div class="clear"></div>
         <%#= link_to 'Show', trend %>
         <%#= link_to 'Edit', edit_trend_path(trend) %>
         <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>

       </li>
       <%end%>
     <% end %>
  </ul>

  <%end%>
</div>

app/views/trends/edit.html.erb
<h1>Editing trend</h1>

<%= render 'form' %>

<%= link_to 'Show', @trend %> |
<%= link_to 'Back', trends_path %>

app/views/trends/index.html.erb
 <% content_for :right_menu do%>
  <br/><br/>
    <span class="section_title">Sort by: </span>
    <ul class="trend_filters">
      <% filters = ["recent","popular", "today", "past_week", "past_month", "men", "women"]%>
      <% filters.each do |filter| %>
        <% if params[:filter] == filter%>
          <%= link_to trends_path(:filter => filter), :class=>"filter-link", :id=>"active-filter" do%>
            <li class="filter">
                 <span><%= filter.humanize %> </span>
            </li>
          <%end%>
        <%else%>
          <%= link_to trends_path(:filter => filter), :class=>"filter-link" do%>
            <li class="filter">
                 <span><%= filter.humanize %> </span>
            </li>
          <%end%>
        <%end%>
      <%end%>
    </ul>
  <%end%>

<div class="content" id="trends">
  <div class="title"><span>What's Trending? </span> </div>
  <ul class="trends_list">
  <% @trends.each do |trend| %>
    <% if !trend.post_contents.blank? %>
    <li class="trend">
    <div class="trend_title"># <%= link_to trend.name, trend_path(trend.name), :id=> "trend"%></div>
    <div class="clear"></div>
      <div class="trend_info fl">
        <span style="font-size: 25px; font-weight:bold;"><%= trend.trend_count %></span> People trending<br/>
        <span style="font-size: 25px; font-weight:bold;"><%= trend.entry_feeds.count%></span> Blogs trending<br/>
        <span style="font-size: 25px; font-weight:bold;"><%= trend.like_count%></span> Likes
      </div>
      <div class="trend_contents fl">
        <div class="trend_list fl">
          <div class="subsection_title">Recent Posts: </div>
          <ul class="list_items">
            <% trend.post_contents.each do |post| %>
            <% post.posts.each do |p|%>
              <% if !p.blank? || p != ""%>
                <% @link_post = p%>
              <%end%>
            <%end%>
            <li>  <%= link_to post.content, post_path(@link_post), :id=> "post" %><br/></li>
            <% end%>
          </ul>
        </div>
        <div class="trend_list fl">
          <div class="subsection_title">Recent Blogs: </div>
          <ul class="list_items">
            <% trend.entry_feeds.each do |entry| %>
            <li>  <%= link_to entry.title, blog_path(entry), :id=> "entry" %><br/></li>
            <% end%>
          </ul>
        </div>
      </div>


      <div class="clear"></div>
      <div class="trend_hops" class="fl">
        <span class="trend_section_info fl">Hop to a related trend: </span>
        <ul class="trend_hop fl">
          <% trend.trends.order("trend_count DESC").limit(6).each do |hop| %>
          <li>  <%= link_to hop.name, trend_path(hop.name), :id => "trend" %><br/></li>
          <% end%>
        </ul>
      </div>
      <div class="clear"></div>
      <%#= link_to 'Show', trend %>
      <%#= link_to 'Edit', edit_trend_path(trend) %>
      <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>

    </li>
    <%end%>
  <% end %>
  </ul>
</div>

app/views/trends/new.html.erb
<h1>New trend</h1>

<%= render 'form' %>

<%= link_to 'Back', trends_path %>

app/views/trends/show.html.erb
<div id="trend_show">
  <div class="trend-title">
    <span id="title"># <%= @trend_search.humanize %> </span>
    <% if is_follow_trend(@trends.first).blank? %>
    <%= link_to follow_trends_path(:id => @trends.first.id), :class=>"fr" do%>
      <div role="button" class="follow-button">Add to Favorites</div>
    <%end%>
  <%else%>
    <%= link_to unfollow_trends_path(:id => @trends.first.id), :class=>"fr" do%>
      <div role="button" class="unfollow-button">Remove from Favorites</div>
    <%end%>
  <%end%>
  </div>
  <div class="trend-info">
    <div id="category">
      <%= pluralize(like_counts(@trends), "person", "people") %> like <%= @trend_search.humanize%>
    </div>
    <div id="category">
      <%= pluralize(trend_counts(@trends), "person is", "people are") %> trending <%= @trend_search.humanize%>
    </div>
    <div id="count">
      <%= pluralize(blog_counts(@trends), "blog is", "blogs are") %> trending <%= @trend_search.humanize%>
    </div>
  </div>
  <div class="clear"></div>

  <% content_for :right_menu do%>
    <span class="section_title">Hop to another trend: </span>
    <ul id='trend_list'>

      <% if @trend_hops.blank? %>
      <li class="trend_item" style="margin-left: auto; margin-right: auto;">
        <p>There are no Trends to hop to! </p>
      </li>
      <% else%>
      <% @trend_hops.each do |trend|%>
      <li class="trend_item fl">
        <div class="trend-row">
          <span id="hop-title"><%= link_to trend.name, trend_path(trend.name) %></span>
        </div>
        <div class="trend-row">
          <span id="hop-count"><%= pluralize(trend.trend_count, "person" )%> trending this. </span>
        </div>
      </li>
      <% end%>
      <div class="clear">
      <% end%>
    </ul>
  <%end%>

  <div class="clear"></div>

  <div class="fl trend_posts">
    <span class="title">What People are saying: </span>
    <%= render :partial => "posts/content"%>
  </div>
  <div class="fl trend_posts">
    <span class="title">Blogs containing <%=@trend_search%> </span>
    <%= render :partial => "blogs/content"%>
  </div>
    <div class="clear"></div>
</div>