config/routes.rb
Trendhop::Application.routes.draw do

  resources :feeds do
    collection do
      get 'subscribe'
      post :subscribe
      get 'unsubscribe'
      post :unsubscribe

      get 'create_feed'
      post :create_feed
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :friends do
    collection do
      get :create, :as => :create
      delete :destroy, :as => :destroy
    end
  end

  resources :groups

  resources :friends

  resources :search

  resources :posts do
    collection do
      get 'like'
      post :like
      get 'unlike'
      post :unlike
      get 'retrend'
      post :retrend
      get 'untrend'
      post :untrend
      get 'hide'
      post :hide
    end
    resources :comment_posts
  end

  resources :trends do
    collection do
      get 'follow'
      post :follow
      get 'unfollow'
      post :unfollow
    end
  end

  match 'blogs/refresh' => 'blogs#refresh'
  resources :blogs do
    collection do
      get 'filter'
      post :filter
    end
    resources :trends
  end

  resources :users do
    resources :blogs
  end

  root :to => 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  belongs_to :retrend_user, :class_name => "User", :foreign_key => :retrend_user_id

  belongs_to :post_content
  has_many :trends, :through => :post_content

  has_many :post_contents

  belongs_to :entry_feed

  has_many :comment_posts, :dependent => :destroy

  has_many :user_likes, :as => :likeable

  scope :no_retrends, :conditions => {:retrend => false}


  # you could put that in the product model
  #
  # class Product
  #   def self.favorites(user)
  #     # stuff
  #   end
  # end
  #
  # Product.favorites(@user)

  # class User
  #   has_many :products do
  #     def favorites
  #       proxy_owner.figure_out_favorites
  #     end
  #   end
  # end

#!!!!  scope :favorites lambda{|user, product|  where(:some_field => user.generate_favorites_list)} will work like this :    Product.where(:blah => test).favorites(@user, @product).order("blue")


  scope :friends, lambda {|user| where(:user_id => user.friends)}

  def delete_chars
    self.delete("!").delete("@").delete("#").delete("*").delete("(").delete(")").delete(",").delete(".").delete("-")
  end

  def retrended?(user)
   # raise user.posts.inspect
    if self.user == user
      return 0
    elsif user.posts.where(:retrend_post_id => self.id).exists?
      return 1
    else
      return 2
    end
  end

  def liked?(user)
  #  if self.user == user
   #   return "own_post"
 #   elsif user.likes.where(:post_id => self.id).exists?
    if user.user_likes.where(:source_type => "Post", :source_id => self.id).exists?
      return "liked"
    else
      return "not_liked"
    end
  end

  def trends_list
    self.trends.map(&:name).to_sentence
  end

  def trend_hop
    array = []
    self.trends.order("trend_count DESC").each do |trend|
      trend.trend_hops.limit(5).each do |hop|
        if !self.trends.include?(hop.trend) && !array.include?(hop.trend)
          array << hop.trend
        end
      end
    end
    return array
  end

  define_index do
    indexes post_content.content
    indexes [user.first_name, user.last_name], :as => :user_name
    indexes trends(:name), :as => :trend
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
#  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search params[:search]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
 #   render :layout => "post_show"
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post_content = PostContent.new()
    @post = Post.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /retrends
  #POST /retrends.json
  def retrend
    session[:return_to] ||= request.referer
    retrend = Post.where(:id => params[:post_id]).first

    @post = Post.new(:post_content_id => retrend.post_content_id, :entry_feed_id => retrend.entry_feed_id, :retrend_user_id => retrend.user_id, :retrend_post_id => retrend.id, :user_id => @current_user.id, :retrend => true)

    retrend.increment(:retrend_count)

    respond_to do |format|
      if @post.save
        retrend.save

        retrend.trends.each do |t|

          @trend = Trend.where(:name => t.name).first
          @trend.increment(:trend_count)
          @trend.save

          @user_trend = UserTrend.where(:user_id => @current_user, :trend_id => @trend).first
          if @user_trend.blank?
            @user_trend = UserTrend.new()
            @user_trend.user_id = @current_user.id
            @user_trend.trend_id = @trend.id
          end

          @user_trend.increment(:count)
          @user_trend.save
        end

        format.html { redirect_to session[:return_to], :notice => 'Post was successfully retrended!' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /untrends
  #DELETE /untrends.json
  def untrend
    session[:return_to] ||= request.referer
    untrend = Post.where(:user_id => current_user.id, :retrend => true, :retrend_post_id => params[:post_id]).first
    untrend.trends.each do |t|
      @trend = Trend.where(:name => t.name).first
      @trend.decrement(:trend_count)
      @trend.save
      @user_trend = UserTrend.where(:user_id => @current_user, :trend_id => @trend).first

      @user_trend.decrement(:count)
      @user_trend.save
    end

    respond_to do |format|
      if untrend.destroy
        format.html { redirect_to session[:return_to], :notice => 'Post was successfully Un-Trended.' }
        format.json { head :ok }
      else
        format.html { redirect_to session[:return_to], :notice => 'There was a problem Un-Trending your post!' }
        format.json { head :ok }
      end
    end
  end

  # /GET Hide Post
  #/POST hide Post
  def hide
    session[:return_to] ||= request.referer
    hide_trend = Post.find(:id => params[:id])

  end

  # POST /posts
  # POST /posts.json
  def create
    # raise params.inspect
    @post_content = PostContent.new(params[:post][:post_content])
    @post_content.save
    @post = Post.new(:user_id => params[:post][:user_id], :post_content_id => @post_content.id, :entry_feed_id => params[:post][:entry_feed_id], :retrend => false)

    at_array =[]
    trend_array=[]

    if params[:post][:trends].blank?
      @post.post_content.content.split(" ").each do |str|
        if str.include?("#")
          trend = delete_chars(str)
          trend_array << trend if !trend_array.include?(trend)
        end
      end
    else
      if params[:post][:trends] != "[]"
        trends = params[:post][:trends].split(",")
        trends.each do |tr|
          trend2 = delete_chars(tr)
          trend_array << trend2 if !trend_array.include?(trend2) && !trend2.blank?
        end
      end
    end
      # if str.include?("@")
      #   str.delete("@")
      #
      #   at_array <<
      # end


    respond_to do |format|
      if (!trend_array.blank? && @post.save) || (@post.save && !@post.entry_feed_id.blank?)
        trend_array.each do |t|
          @trend = Trend.where(:name => t).first
          if @trend.blank?
            @trend = Trend.new()
            @trend.name = t
            @trend.like_count = 0
          end
          @trend.increment(:trend_count)
          @trend.save

          if !@post.entry_feed_id.blank?
            entry_feed = EntryFeed.where(:id =>@post.entry_feed_id).first
            entry_feed.increment(:trend_count)
          end

          @user_trend = UserTrend.where(:user_id => @current_user, :trend_id => @trend).first
          if @user_trend.blank?
            @user_trend = UserTrend.new()
            @user_trend.user_id = @current_user.id
            @user_trend.trend_id = @trend.id
          end
            @user_trend.increment(:count)
            @user_trend.save

          hop_array = trend_array.reject{ |a| a== t}

          hop_array.each do |hop|
            @hop = Trend.where(:name => hop).first

            @trend_hop = TrendHop.where(:trend_id => @trend.id, :related_trend_id => @hop.id).first unless @hop.blank?
            if @trend_hop.blank?
              @trend_hop = TrendHop.new()
              @trend_hop.trend_id = @trend.id
              if @hop.blank?
                @hop = Trend.new()
                @hop.name = hop
                @hop.save
              end
              @trend_hop.related_trend_id = @hop.id
            end
            @trend_hop.increment(:count)
            @trend_hop.save
          end

          @post_trend = PostTrend.where(:post_content_id => @post_content, :trend_id => @trend).first
          if @post_trend.blank?
            @post_trend = PostTrend.new()
            @post_trend.trend_id = @trend.id
            @post_trend.post_content_id = @post_content.id
          end
          @post_trend.save

        end

        format.html { redirect_to root_path, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        @post_content.destroy
        @post.destroy
        format.html { redirect_to root_path, :notice => 'You must include a trend!'}
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    session[:return_to] ||= request.referer
  #  @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to session[:return_to] }
      format.json { head :ok }
    end
  end

  def like
    session[:return_to] ||= request.referer
    @likeable = find_likeable.last
    @likeable_type = find_likeable.first
    @user_like = UserLike.new(:user_id => current_user.id, :source_id => @likeable.id, :source_type => @likeable_type)

    current_url = request.url

    if @user_like.save
      flash[:notice] = "Oh you like it!"
      redirect_to session[:return_to]
    else
      flash[:notice] = "There was an error!!!!"
     redirect_to session[:return_to]
    end
  end

  def unlike
    session[:return_to] ||= request.referer
    @likeable = find_likeable.last
    @likeable_type = find_likeable.first

    @user_like = UserLike.where(:user_id => current_user.id, :source_id => @likeable.id, :source_type => @likeable_type).first
    if @user_like.blank?
      @user_like = UserDislike.where(:user_id => current_user.id, :source_id => @likeable.id, :source_type => @likeable_type).first
    end

    @user_like.destroy

    respond_to do |format|
      format.html {redirect_to root_path }
      format.json {head :ok}
    end

  end

  def dislike
    session[:return_to] ||= request.referer
    @likeable = find_likeable.last
    @likeable_type = find_likeable.first
    @user_like = UserDislike.new(:user_id => current_user.id, :source_id => @likeable.id, :source_type => @likeable_type)

      current_url = request.url

      if @user_like.save
        flash[:notice] = "Oh you like it!"
        redirect_to session[:return_to]

      else
        flash[:notice] = "There was an error!!!!"
       redirect_to session[:return_to]

      end
  end

  private

  def delete_chars(trend)
    trend.delete("!").delete("@").delete("#").delete("*").delete("(").delete(")").delete("?").delete(".").delete(",").delete("<").delete(">").delete("/").delete('\\').delete("-")
  end

  def find_likeable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return [$1.classify, $1.classify.constantize.find(value)]
      end
    end
    nil
  end


end

app/helpers/posts_helper.rb
module PostsHelper

  def delete_chars(trend)
    trend.delete("!").delete("@").delete("#").delete("*").delete("(").delete(")").delete("?").delete(".").delete(",").delete("<").delete(">").delete("/").delete('\\')
  end

end

app/views/posts/_content.html.erb
<div class="content" id="post_index">
  <% if @posts.blank? %>
    <h3>There are no posts!</h3>
  <%else%>
  <ul class="posts_list">

  <% @posts.each do |post| %>
  <% if !post.retrend?%>
    <li class="post">
      <div class="post_content">
        on <%= post.created_at.to_s(:mdy_dots) unless post.created_at.blank?%>

        <div style="width: 100%;">
          <%if !post.retrend %>
            <div class="fr">
              <%= link_to "Retrend", retrend_posts_path(:post_id => post.id)%>
            </div>
            <% end%>
            
            <!--
            <%# if  !post.retrend_count.blank? %>
            <div class="fr">
              <%#= pluralize(post.retrend_count, "person has", "people have")%> re-trended this.
            </div>
            <%# end%>
            -->

          <div class="content"> <%= post.post_content.content %> </div>
            <div class="clear"></div>
      </div>

    <!--
      <div class="post_info fl">
        <%# post.retrend_post_id.blank? ? posted = post : posted = Post.where(:id => post.retrend_post_id).first %>
        <%# posted.trends.each do |trend| %>
        <span> <%#= pluralize(trend.trend_count, "person is", "people are") %> trending <%#= trend.name%>.</span>
        <%#end%>
      </div>
      <div class="trend_hops fl">
        <span class="subsection_title">Hop to related trends: </span>
        <ul class="trend_hop">
          <%#  post.trend_hop.each do |hop|%>
            <li class="fl" id='hop'>  <%#= link_to hop.name, trend_path(hop.name) %></li>
          <%# end%>
          <%# if post.trend_hop.blank?%>
            <li>-- none -- </li>
          <%# end%>

        </ul>
      </div>
      -->  
      
      <div class="clear"></div>
      <%#= link_to 'Show', trend %>
      <%#= link_to 'Edit', edit_trend_path(trend) %>
      <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>

    </li>
  <% end %>
  </ul>

  <%end%>
  <%end%>
</div>

app/views/posts/_form.html.erb
<%= form_for [@post, @post_content] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>
  <!-- <div class="field">
    <%#= f.label :category_id %><br />
    <%#= f.number_field :category_id %>
  </div> -->
  <div class="field" >
    <%= f.text_area @post_content.content, :rows=>'4', :style=>"width:550px;" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <hr/>
<% end %>

app/views/posts/_index.html.erb
<div class="content" id="post_index">
  <% if @posts.blank? %>
    <h3>There are no posts!</h3>
  <%else%>
  <ul class="posts_list">

    <% @posts.each do |post| %>
      <li class="post">
        <% @post1 = post %>
        <% if @post1.entry_feed_id.blank? %>
          <%= render :partial => "posts/post" %>
        <%else%>
          <%= render :partial => "posts/post_with_blog" %>
        <%end%>

      </li>
        <div class="clear"></div>
    <% end %>
  </ul>


  <%end%>
</div>




</div>

app/views/posts/_post.html.erb
      <div class="post_content fl">
        <div class="post_title">
          <%# raise @post1.inspect%>
          <%= link_to @post1.user.full_name, user_path(@post1.user), :id=>"name"%> <%= @post1.retrend_post_id.blank? ? "is trending " : "is RE-trending " %> <%= raw(list_trends(@post1)) %>

          <% if @post1.retrend%>
            <span class=''>from <%= link_to @post1.retrend_user.full_name, user_path(@post1.retrend_user_id)%> </span>
          <% end%>

        </div>
        <div class="fl post-date">
          <div class="time">
            <%= @post1.created_at.to_s(:time_only) unless @post1.created_at.blank?%>
          </div>
          <div class="date">
            <%= @post1.created_at.to_s(:date_only) unless @post1.created_at.blank?%>
          </div>
          <div class="year">
            <%= @post1.created_at.to_s(:year_only) unless @post1.created_at.blank?%>
          </div>
        </div>
        <div class="content fl"> <%= @post1.post_content.content %> </div>
        <div class="clear"></div>

      </div>

      <div class="fl over_section">
        <%= link_to post_path(@post1), :class=>"post-link" do%>
          >>
        <%end%>
      </div>
      <div class="clear"></div>

      <div class="post_bottom_section">
        <div class="post_info fl">
          <%#if !@post1.retrend %>
            <div class="button1">
            <% case @post1.retrended?(current_user) %>
              <% when 0%>
              <%when 1%>
                <%= link_to untrend_posts_path(:post_id => @post1.id) do%>
                  <div role="button" class="untrend-button">Un-Trend</div>
                <%end%>
              <%when 2%>
                <%= link_to retrend_posts_path(:post_id => @post1.id) do%>
                  <div role="button" class="retrend-button">Re-Trend</div>
                <% end%>
            <%end%>
            <% if @post1.user == current_user%>
              <%= link_to hide_posts_path(:post_id => @post1.id), :confirm => 'Do you want to make this post disappear?' do%>
                <div role="button" class="untrend-button">Hide Post?</div>
              <%end%>
            <%end%>
            </div>
          <%# end%>
          <% if  !@post1.retrend_count.blank? %>
            <div>
              <div class="clear"></div>
                <%= pluralize(@post1.retrend_count, "person", "people") %> re-trended.
            </div>
          <% end%>

          <div class="button1">
          <% case @post1.liked?(current_user) %>
            <% when "liked" %>
             <%= link_to unlike_posts_path(:post_id => @post1.id), :confirm => 'Do you want to make this post disappear?' do%>
                <div role="button" class="untrend-button">Unlike</div>
              <%end%>
            <% when "not_liked"%>
             <%= link_to like_posts_path(:post_id => @post1.id) do%>
                <div role="button" class="retrend-button">Like</div>
              <%end%>
            <% when "own_post" %>

          <%end%>
          </div>
          <div class="trend_hops fl">
            <span class="subsection_title">Hop to related trends: </span>
            <ul class="trend_hop">
              <%  @post1.trend_hop.each do |hop|%>
                <li class="fl" id='hop'>  <%= link_to hop.name, trend_path(hop.name) %></li>
              <% end%>
              <% if @post1.trend_hop.blank?%>
                <li>-- none -- </li>
              <% end%>
            </ul>
          </div>

            <!-- shows number of people trending each TREND -->
          <!-- <%# @post1.retrend_post_id.blank? ? posted = post : posted = Post.where(:id => @post1.retrend_post_id).first %>
                  <%# posted.trends.each do |trend| %>
                  <span> <%#= pluralize(trend.trend_count, "person is", "people are") %> trending <%#= trend.name%>.</span>
                  <%#end%> -->
        </div>

        <%#= link_to 'Show', trend %>
        <%#= link_to 'Edit', edit_trend_path(trend) %>
        <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>
        <div class="fl" id="comments_index">
          <div class="comments">
            <% @post1.comment_posts.each do |comment| %>
              <div class="comment-item">
                <span class="comment-user"><%= link_to comment.user.full_name, user_path(comment.user), :id =>"user" %> commented: </span>
                <p class="comment-body"><%= comment.body%></p>
              </div>
            <% end%>
          </div>

          <div class="post_comments">
            <%= form_for([@post1, @post1.comment_posts.build]) do |f| %>
              <%= f.hidden_field :commenter, :value => current_user.id %>
              <div class="field">

                <%= f.text_area :body %>
              </div>
              <div class="actions">
                <%= f.submit(:value => "Comment") %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clear"></div>
    </div>

app/views/posts/_post_with_blog.html.erb
<div class="post_content fl">

  <div class="post_title">

          <%# raise @post1.inspect%>
          <%= link_to @post1.user.full_name, user_path(@post1.user), :id=>"name"%> <%= @post1.retrend_post_id.blank? ? "is trending " : "is RE-trending " %>

            <% if list_trends(@post1) == "" %>
              a link from <b><%= @post1.entry_feed.feed.name unless @post1.entry_feed.blank?%></b>
            <% else%>
              <%= raw(list_trends(@post1)) %> with a link from <b><%= @post1.entry_feed.feed.name unless @post1.entry_feed.blank?%></b>
            <%end%>

          <% if @post1.retrend%>
            <span class=''>from <%= link_to @post1.retrend_user.full_name, user_path(@post1.retrend_user_id)%> </span>
          <% end%>
  </div>

  <div class="fl post-date">
          <div class="time">
            <%= @post1.created_at.to_s(:time_only) unless @post1.created_at.blank?%>
          </div>
          <div class="date">
            <%= @post1.created_at.to_s(:date_only) unless @post1.created_at.blank?%>
          </div>
          <div class="year">
            <%= @post1.created_at.to_s(:year_only) unless @post1.created_at.blank?%>
          </div>
  </div>

  <div class="content fl">
        <%= @post1.post_content.content %><br/>
        <div class="content_blog">
            <% @entry = EntryFeed.where(:id => @post1.entry_feed_id).first%>
            <div class="blog_title">
              <%= link_to @entry.title, blog_path(@entry.id)%>
            </div>
            <div class="blog_content">
              <% summary = strip_tags(raw(@entry.summary)) %>
              <%= truncate summary, :length => 190 %>
            </div>
        </div>
  </div>

  <div class="clear"></div>

</div>

<div class="fl over_section">
  <%= link_to post_path(@post1), :class=>"post-link" do%>
      >>
  <%end%>
</div>

  <div class="clear"></div>

<div class="post_bottom_section">
    <div class="post_info fl">


          <%#if !@post1.retrend %>
        <div class="button1">
            <% case @post1.retrended?(current_user) %>
              <% when 0%>
              <%when 1%>
                <%= link_to untrend_posts_path(:post_id => @post1.id) do%>
                  <div role="button" class="untrend-button">Un-Trend</div>
                <%end%>
              <%when 2%>
                <%= link_to retrend_posts_path(:post_id => @post1.id) do%>
                  <div role="button" class="retrend-button">Re-Trend</div>
                <% end%>
            <%end%>
            <% if @post1.user == current_user%>
              <%= link_to hide_posts_path(:post_id => @post1.id), :confirm => 'Do you want to make this post disappear?' do%>
                <div role="button" class="untrend-button">Hide Post?</div>
              <%end%>
            <%end%>
        </div>
          <%# end%>
        <% if  !@post1.retrend_count.blank? %>
        <div>
            <div class="clear"></div>
            <%= pluralize(@post1.retrend_count, "retrend", "retrends") %>
        </div>
        <% end%>

      <div class="button1">
          <% case @post1.liked?(current_user) %>
            <% when "liked" %>
             <%= link_to unlike_posts_path(:post_id => @post1.id) do%>
                <div role="button" class="untrend-button">Unlike</div>
              <%end%>
            <% when "not_liked"%>
             <%= link_to like_posts_path(:post_id => @post1.id) do%>
                <div role="button" class="retrend-button">Like</div>
              <%end%>
            <% when "own_post" %>

          <%end%>
      </div>

      <div>
        <div class="clear"></div>
        <%= pluralize(@post1.like, "like", "likes") %>
      </div>


      <div class="trend_hops fl">
            <span class="subsection_title">Hop to related trends: </span>
            <ul class="trend_hop">
              <%  @post1.trend_hop.first(5).each do |hop|%>
                <li class="fl" id='hop'>  <%= link_to hop.name, trend_path(hop.name) %></li>
              <% end%>
              <% if @post1.trend_hop.blank?%>
                <li>-- none -- </li>
              <% end%>
            </ul>
      </div>

            <!-- shows number of people trending each TREND -->
          <!-- <%# @post1.retrend_post_id.blank? ? posted = post : posted = Post.where(:id => @post1.retrend_post_id).first %>
                  <%# posted.trends.each do |trend| %>
                  <span> <%#= pluralize(trend.trend_count, "person is", "people are") %> trending <%#= trend.name%>.</span>
                  <%#end%> -->

</div>


        <%#= link_to 'Show', trend %>
        <%#= link_to 'Edit', edit_trend_path(trend) %>
        <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>

<div class="fl" id="comments_index">

          <div class="comments">
            <% @post1.comment_posts.each do |comment| %>
              <div class="comment-item">
                <span class="comment-user"><%= link_to comment.user.full_name, user_path(comment.user), :id =>"user" %> commented: </span>
                <p class="comment-body"><%= comment.body%></p>
              </div>
            <% end%>
      </div>

      <div class="post_comments">
            <%= form_for([@post1, @post1.comment_posts.build]) do |f| %>
              <%= f.hidden_field :commenter, :value => current_user.id %>
              <div class="field"><%= f.text_area :body %></div>
              <div class="actions"><%= f.submit(:value => "Comment") %></div>
            <% end %>

          </div>
</div>

  <div class="clear"></div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="content" id="post_index">
  <div class="title"><span><%= @header_title %></span> </div>
  <ul class="posts_list">

  <% @posts.each do |post| %>
    <li class="post">

      <div class="post_content">
        <div class="post_title">
          <%= link_to post.user.full_name, user_path(post.user), :id=>"name"%> <%= post.retrend_post_id.blank? ? "is trending " : "is RE-trending " %> <%= raw(list_trends(post)) %>

          <% if post.retrend%>
            <span class='fr'>from <%= link_to post.retrend_user.full_name, user_path(post.retrend_user_id)%> </span>
          <% end%>

          </div>
          on <%= post.created_at.to_s(:mdy_dots) unless post.created_at.blank?%>

          <div style="width: 100%;">
            <%if !post.retrend %>
            <div class="fr">
              <%= link_to "Retrend", retrend_posts_path(:post_id => post.id)%>
            </div>
            <% end%>
            <% if  !post.retrend_count.blank? %>
            <div class="fr">
              <%= pluralize(post.retrend_count, "person has", "people have")%> re-trended this.
            </div>
            <% end%>

          <div class="content"> <%= post.post_content.content %> </div>
            <div class="clear"></div>
      </div>

      <div class="post_info fl">
        <% post.retrend_post_id.blank? ? posted = post : posted = Post.where(:id => post.retrend_post_id).first %>
        <% posted.trends.each do |trend| %>
        <span> <%= pluralize(trend.trend_count, "person is", "people are") %> trending <%= trend.name%>.</span>
        <%end%>
      </div>
      <div class="trend_hops fl">
        <span class="subsection_title">Hop to related trends: </span>
        <ul class="trend_hop">
          <%  post.trend_hop.each do |hop|%>
            <li class="fl" id='hop'>  <%= link_to hop.name, trend_path(hop.name) %></li>
          <% end%>
          <% if post.trend_hop.blank?%>
            <li>-- none -- </li>
          <% end%>

        </ul>
      </div>
      <div class="clear"></div>
      <%#= link_to 'Show', trend %>
      <%#= link_to 'Edit', edit_trend_path(trend) %>
      <%#= link_to 'Destroy', trend, :confirm => 'Are you sure?', :method => :delete %>

    </li>
  <% end %>
  </ul>



</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>